# Generated by Django 3.2.6 on 2021-08-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210813_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.CharField(blank=True, default='1921', max_length=4),
        ),
    ]
