# Generated by Django 3.2.6 on 2021-08-13 17:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210813_1704'),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('BO', 'Booked'), ('IS', 'In Service'), ('FX', 'Fixed'), ('CL', 'Collected'), ('UR', 'Unrepairable')], default='BO', max_length=2)),
                ('comments', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateField(default=datetime.datetime.now)),
                ('total_cost', models.FloatField()),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
                ('mechanic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.mechanic')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.AddField(
            model_name='appointment',
            name='service_type',
            field=models.ManyToManyField(blank=True, related_name='service_type', to='appointments.Service'),
        ),
    ]
