# Generated by Django 3.2.6 on 2021-08-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210813_1742'),
        ('appointments', '0002_auto_20210813_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='customer',
        ),
        migrations.AddField(
            model_name='appointment',
            name='customer',
            field=models.ManyToManyField(blank=True, related_name='appointment_customer', to='users.Customer'),
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='mechanic',
        ),
        migrations.AddField(
            model_name='appointment',
            name='mechanic',
            field=models.ManyToManyField(blank=True, related_name='appointment_mechanic', to='users.Mechanic'),
        ),
    ]
