# Generated by Django 3.2.6 on 2021-08-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_auto_20210813_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='scheduled_at',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
